all:
	gcc demo.c -lucp -lucs -I/global/home/users/ziyi/ucx-source/install/include -L/global/home/users/ziyi/ucx-source/install/lib -g -Wl,-rpath,/global/home/users/ziyi/ucx-source/install/lib -o demo

clean:
	rm -f demo 
